[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Worker service configuration
[[services]]
name = "worker"
startCommand = "bundle exec sidekiq"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10